name: njsscan sarif
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: njsscan code scanning
    steps:

    - name: Checkout the code
      uses: actions/checkout@v4.2.1

    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@v7
      with:
        args: '. --sarif --output results.sarif || true'

        
    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif